package com.streamify.app.security

import android.util.Log
import java.security.SecureRandom
import javax.crypto.Cipher
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

/**
 * Phase 7 · Step 7.2 — AES-256-GCM encrypt / decrypt utility.
 *
 * Two usage modes:
 *  1. **Build-time constants** — [decryptBuildTime] reconstructs the
 *     XOR-obfuscated key from [EncryptedConstants] and decrypts.
 *  2. **Runtime data** — [encrypt] / [decrypt] use a [SecretKey] from
 *     [KeystoreManager] for encrypting ephemeral tokens, cache blobs,
 *     or any data that should not outlive the process.
 *
 * All decrypted values are returned as [CharArray] to avoid polluting
 * the JVM String intern pool.  Call [wipe] when the value is no longer
 * needed.
 */
internal object StringEncryptor {

    private const val TAG = "StringEncryptor"
    private const val TRANSFORMATION = "AES/GCM/NoPadding"
    private const val GCM_TAG_BITS = 128
    private const val IV_BYTES = 12

    // ── Build-time decryption ──────────────────────────────────────

    /**
     * Decrypt a value that was encrypted at build time by the
     * `:app:encryptSecrets` Gradle task.  The key is reconstructed
     * from the XOR-obfuscated byte arrays in [EncryptedConstants].
     */
    fun decryptBuildTime(iv: ByteArray, ciphertext: ByteArray): CharArray {
        val keyBytes = EncryptedConstants.reconstructKey()
        val secretKey = SecretKeySpec(keyBytes, "AES")
        val result = decrypt(iv, ciphertext, secretKey)
        // Wipe the reconstructed key bytes immediately.
        keyBytes.fill(0)
        return result
    }

    // ── Runtime encrypt / decrypt (Keystore-backed) ────────────────

    /**
     * Encrypt [plaintext] with [key] (from [KeystoreManager]).
     * Returns `(iv, ciphertext)` — the IV is 12 bytes, generated by
     * [SecureRandom].
     */
    fun encrypt(plaintext: CharArray, key: SecretKey): Pair<ByteArray, ByteArray> {
        val iv = ByteArray(IV_BYTES).also { SecureRandom().nextBytes(it) }
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key, GCMParameterSpec(GCM_TAG_BITS, iv))
        val ct = cipher.doFinal(plaintext.concatToString().toByteArray(Charsets.UTF_8))
        return Pair(iv, ct)
    }

    /**
     * Decrypt [ciphertext] with [key] (from [KeystoreManager]).
     * The [iv] must match the one returned by [encrypt].
     */
    fun decrypt(iv: ByteArray, ciphertext: ByteArray, key: SecretKey): CharArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_BITS, iv))
        val bytes = cipher.doFinal(ciphertext)
        return String(bytes, Charsets.UTF_8).toCharArray()
    }

    // ── Secure wipe helpers ────────────────────────────────────────

    /** Overwrite every element of [array] with the null character. */
    fun wipe(array: CharArray) {
        array.fill('\u0000')
    }

    /** Overwrite every element of [array] with zero. */
    fun wipe(array: ByteArray) {
        array.fill(0)
    }
}
